### ISSUE TITLE
Additional Tracking (enhancement)

### ISSUE THREAD

**Issue by leede99** [xurion/ffxi-empy-pop-tracker#12]
Tinnin
Sarameya
Tyger
Pandemonium Warden

Adding these as trackable NM "paths" would be a welcome addition.  The main issue I foresee would be the 'optimum path' as not all NMs are required to complete pop set Key Item.  The other twist is when you get an item from Nyzul that can make various KI's as well.
 - example1: Tinnin: (Cheese Hoarder > Maroon >> Lividroot > Apple) repeat x3 >> Gears/Charcoal, Gotoh/DeepPurple, Dea/Chestnut
 - example2: Tinnin: Vulpangue Wing from Nyzul > Maroon >> Iriz Ima > Apple >> (Vulpangue > Maroon >> Iriz Ima > Apple) and repeat >> Gears/Charcoal, Gotoh/DeepPurple, Dea/Chestnut

**Comment by xurion** [comment]
Hey thanks for the request.

You're right about the optimal path. I wouldn't want to guess which NM the user wanted to go for, even if there was an optimal/quicker route, so it would need to list all possibilities. This is different to the existing data structure and may require some work to allow this new layout.

I'll have a think and see if I can come up with a layout that makes sense.

**Comment by xurion** [comment]
ZNM pop tree: https://www.bg-wiki.com/images/1/1a/Znmfinal.jpg

**Comment by leede99** [comment]
I have been thinking about it a while, and, not knowing how hard or easy (non-programmer --just a dreamer :P, but was thinking about using your current nested functions, but put a "wrapper" if you have the correct colored seal KI.  Still list all paths, but if seal KI, show that section as green (similar to how you show completed pop set now).  And just have 3 sections [1 for each tier).

So it could work something like this (using my previous Tinnin example):
        Tier 1: Vulpangue            | Chamrosh          | Cheese Hoarder Gigiroon
  Pop Item: Hellcage Butterfly | Floral Nectar      | Rodent Cheese
Drop Item: Vulpangue Wing   | Chamrosh Beak | Gigiroon's Cape
  Location: Wajaom > D10      | ?Mamook> J10  | SP Nyzul > E/F8/9

Where each |column| would have it's own "highlight" when you have the item.
 - Example: if you have the POP item, highlight it;  if you have the DROP item, highlight it
 -- added want/bonus: when in the Zone (Location), highlight it

Once player has "Maroon Seal" KI, the ENTIRE ROW is highlighted (maroon).

Then a 2nd row for Tier 2, same concept as Tier 1.  After getting "Apple Green Seal", highlight entire row (apple green).

For Tier 3, similar concept highlighting pop/drop items, but since you need all 3 make each column highlight the appropriate color once you get seal KI (Charcoal Grey, Deep Purple, Chestnut).

I hope this helps or gives some insight on how to proceed, but I believe it uses your current system of list, items, highlighting, and tracking   in a way that works for ZNMs.

**Comment by xurion** [comment]
I've thought about this at length. The main issue I see here is adapting the tree-like hierarchy display of EPT to suite that of the ZNM hierarchy.

It is for this reason I think it best that the EPT is not increased in complexity to suite one particular hierarchy model, but instead would suggest that ZNM tracking should be done as a new addon. I may look into this in the future.
