### ISSUE TITLE
Condensed mode

### ISSUE THREAD

**Issue by shastaxc** [xurion/ffxi-empy-pop-tracker#15]
Can we get a condensed mode with less space between mobs, maybe make it bulleted instead (at the top level). And highlight the name of the mob instead of the drop item so that the item can be hidden.

**Comment by xurion** [comment]
Thanks @shastaxc I've been thinking of this due to how some people have their alts in smaller Windower instances. I'll post some previews here once I have something working.

**Comment by xurion** [comment]
Here's the largest list (Chloris) in normal mode and mini mode. What do you think?

![image](https://user-images.githubusercontent.com/606627/92593479-1685b180-f299-11ea-9d12-6651f517321b.png)

![image](https://user-images.githubusercontent.com/606627/92593428-040b7800-f299-11ea-92e4-b38808471fe6.png)

**Comment by xurion** [comment]
Gonna push this ahead with the above changes. The mini mode reduces the height of the addon by ~50% and can be reduced further by modifying the font size in the settings.xml file.

**Comment by xurion** [comment]
PR raised with the Windower repository: https://github.com/Windower/Lua/pull/1947

**Comment by shastaxc** [comment]
Looks great!

**Comment by xurion** [comment]
@shastaxc cool glad you like it! Please be aware that until the Windower PR is merged (linked above) this function will not be available.

I'll chase them to see if it's possible to get this looked at.

**Comment by xurion** [comment]
This is now merged into the Windower distribution.
