### ISSUE TITLE
Suggestion: More logical list order

### ISSUE THREAD

**Issue by SvenBent** [xurion/ffxi-empy-pop-tracker#16]
The pop and NM list currently follows an illogical pattern.

Currently it is: Item > what NM it pops > what subsequent pop item that NM drops.

This means you have to zigzag across the list, because it shows the current NM above the pop item it actually drops. Reversing this order will make it easier to follow.

**Comment by xurion** [comment]
Thanks for raising your issue.

Just to clarify, your suggestion would be to go from:

```
Ciren-Croin

  Cep-Kamuy, Forced (F-4)
    >> Ж Glistening Orobon Liver
      Ancient Orobon (F-5)
        >> Orbn. Cheekmeat

  Heqet, Times (I-6)
    >> Ж Doffed Poroggo Hat
```

to:

```
Ciren-Croin

  Ж Glistening Orobon Liver
    >> Cep-Kamuy, Forced (F-4)
      Orbn. Cheekmeat
        >> Ancient Orobon (F-5)

  Ж Doffed Poroggo Hat
    >> Heqet, Times (I-6)
```

If so, the adjustment to the display logic is simple and I welcome a PR for those changes :)

**Comment by SvenBent** [comment]
TY and yes that is exactly it this way the flow order just goes step by step bottom up and IMHO it just appear more logical

**Comment by xurion** [comment]
Posted this [on ffxiah](https://www.ffxiah.com/forum/topic/54376/empyrean-pop-tracker-addon-10-years-late/#3636576) and everyone that replied preferred the existing way. Closing.
