### ISSUE TITLE
Heroes of Abyssea NM's

### ISSUE THREAD

**Issue by Lilpeoples** [xurion/ffxi-empy-pop-tracker#19]
The Heroes of Abyssea NM's aren't added to the tracker. Ie: Resheph, Amphitrite, and Bennu. Can these be added? This tracker helps out a lot so thank you for what it already tracks.

**Comment by xurion** [comment]
Thanks for raising! I'll look into adding these. The reason they're not in there already is because the addon was originally for Empyrean weapon drop tracking. But has since started to track all manner of NMs.

**Comment by Lilpeoples** [comment]
Thank you kindly. Much appreciated!

**Comment by xurion** [comment]
NMs added. Sorry for the delay. I'll prepare and submit a release for Windower.

**Comment by xurion** [comment]
Added to Windower.

**Comment by Lilpeoples** [comment]
Oh wow thank you 🙏🏾 laugh out loud I thought y’all forgot about it haha
but thank you for the update
