### ISSUE TITLE
Tracking multiple NMs at once

### ISSUE THREAD

**Issue by Noobcakes** [xurion/ffxi-empy-pop-tracker#2]
Would it be possible to allow tracking for more than one NM at a time?

**Comment by xurion** [comment]
Thanks for the suggest! How do you think this should display? Would each tracked NM have it's own draggable text area?

**Comment by Noobcakes** [comment]
That would be great if it's not too much trouble. Whatever gets it on the screen is good enough for me though. Great job on the addon btw. Thanks for releasing this.

EDIT: My buddy just renamed a copy of the addon and loaded two instances as a workaround. So I guess that's an option since farming more than one pop set at a time probably isn't a super common occurrence.

**Comment by xurion** [comment]
Oh nice good thinking! :D
I guess that alleviates the immediate need for it for now but I'll keep this open, as this has a challenge behind it that I'd like to play with in the future.

**Comment by Bedavere** [comment]
Also could add abyssea Tier 2 and Tier 3 Voidwalker NMs(Brulo Etc) to them for soul farming. So that you know you have the KI still at times that it would break.

**Comment by xurion** [comment]
Thanks @Bedavere I've added a new enhancement issue to cover this.

**Comment by neoanguiano** [comment]
could it be possibe to track the item one is farming? ie isgebind hearts

**Comment by xurion** [comment]
Hey @Bedavere I'll add this as a separate feature.

**Comment by xurion** [comment]
I've messed with this a bit and it is possible, however I believe the benefit will only be gained by a minimal number of users. The ease in which you can switch from one NM to the next makes this even less of a worthwhile endeavour, not to mentioned the solution mentioned earlier in the issue about duplicating the directory, should you really want to gain this functionality. Also I find it unlikely, but not impossible, that players would want to farm two NMs at once.

**Comment by xurion** [comment]
@Bedavere - Items of interest feature you mentioned is now implemented.
