### ISSUE TITLE
Load error

### ISSUE THREAD

**Issue by Rresttree** [xurion/ffxi-empy-pop-tracker#31]
![image](https://user-images.githubusercontent.com/123088347/213460849-7fbe3d98-faab-44c7-9ce6-72ecc873c9d0.png)

Hello, Randomly got this error popping up - and unable to figure out how to fix it - ty.

**Comment by Rresttree** [comment]
Disregard - deleted old files.. downloaded new zip with files and it works -- thank you.

**Comment by xurion** [comment]
Ahh thanks :) just so you know, you can download the addon via the Windower launcher if you want automatic updates.
